doc/examples.rst, examples/build_all_examples.py, examples/pygtk_mpl_numpy/.f2py_f2cmap, examples/pygtk_mpl_numpy/README.rst, examples/pygtk_mpl_numpy/grab_files.sh, examples/pygtk_mpl_numpy/gtk_preamble.py, examples/pygtk_mpl_numpy/hellomatplotlib.py, examples/pygtk_mpl_numpy/installer.cfg
I would like to add this example to the repository, that shows how to package pygtk, matplotlib and numpy. It is based on the pygtk-example and an example from the matplotlib-documentation. The whole example seems to only work with 32-bit and Python 2.7.x (Although a more experienced programmer might be able to debug this).
Compared to the other examples this one requires 7zip. I don't know how to do a requirements-check for this in the shell script, so it probably fails if `sh grab_files.sh` is executed on a system without 7zip.
=> Add example for PyGTK with Matplotlib and Numpy

nsist/__init__.py, nsist/copymodules.py
I recently contributed the ``exclude`` configuration option (and of course, tested it) and now, that pynsist 1.5 is released I started using it in production.
However, if used it in a Linux/Windows environment, it is very easy to make the setting ineffective by mixing forward and backward slashes as path seperators.
Additionally, there was a bug which lead to exclusions not working in the root directory of a package because of a ``/./`` in a generated path. Running ``os.path.normpath`` over both package directories and exclusion patterns fixes the problem.
=> Fix a bug in the exclude option in cross-platform environments

doc/examples.rst, examples/build_all_examples.py, examples/pygi_mpl_numpy/1_download.sh, examples/pygi_mpl_numpy/2_extract.sh, examples/pygi_mpl_numpy/README.rst, examples/pygi_mpl_numpy/gnome_preamble.py, examples/pygi_mpl_numpy/installer.cfg, examples/pygi_mpl_numpy/pygi_test.py
A PyGI (or PyGObject) example would be helpful, because packaging this dependency is not trivial and different than for PyGTK.
I could not get the shell script to download the 64-bit numpy package from http://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy - The Readme explains where to manually download it.
=> Add PyGI / PyGObject example

examples/pygi_mpl_numpy/2_extract.sh, examples/pygi_mpl_numpy/README.rst
I updated the script to compile the glib-schemas after all the libraries are copied in the `pynsist_pkgs` folder. The readme explains why the compiling is necessary. Linking to the bug-reports should help people that encounter a crash because of uncompiled schemas.
Relevant bug report:
- https://github.com/takluyver/pynsist/issues/43
=> Update PyGI/PyGObject example to compile glib-schemas

examples/pygi_mpl_numpy/1_download.sh, examples/pygi_mpl_numpy/2_extract.sh, examples/pygi_mpl_numpy/README.rst
This PR updates the `pygi_mpl_numpy` example to rev21 of the Python-GI bundle for Windows. Thanks to @xor for reporting the issue and providing the fix.
The PR resolves this issue:
- https://github.com/takluyver/pynsist/issues/52
I tested the example program on Windows 7 and it did not trigger any warnings.
=> Updating pygi_mpl_numpy example to pygi-aio-rev21

nsist/configreader.py
I had a look at how you were reading and validating the configuration file and it seems this simple modification is enough to avoid having to provide the Python version when we want only to force the bitness (as discussed in #49). I thought it would be more complex, but turns out you already had a fallback prepared.
You mentioned that it defaults to the Python version it is running in, but looks like `DEFAULT_PY_VERSION` is fixed... but I'm not touching there because that is a different issue.
=> Make Python version not mandatory

README.rst, examples/pyqt4/README.md, flit.ini
As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.
=> Convert readthedocs link for their .org -> .io migration for hosted projects

examples/pywebview/README.md, examples/pywebview/download.sh, examples/pywebview/installer.cfg, examples/pywebview/pywin32_paths.py, examples/pywebview/simple_browser.py
I have got this working, but it's decidedly rough:
- Pywin32 is compiled with an older version of the MSVCR (2010), which the user has to [download separately](http://www.microsoft.com/en-us/download/details.aspx?id=14632) and install.
- The resulting application is *really* slow, practically unusable even on a new laptop. The culprit appears to be something in comtypes which generates code containing `True = 1`, which is a syntax error in Python 3. I think that the error loading this generated code causes it to keep trying to generate it again. When I comment that line out, it runs at a reasonable speed.
- Building on Windows probably won't work, because it relies on the bash script fetching and arranging things. It should be easy enough to translate to Python if anyone wants to do that, …
=> Add example using Pywebview

nsist/pyapp.nsi
As the version is required and `${PRODUCT_VERSION}` is already set, it seems like a no-brainer to add the version info :)
=> Add DisplayVersion to the Uninstall info

nsist/__init__.py, nsist/configreader.py, nsist/tests/data_files/valid_config_value_newline.cfg, nsist/tests/test_configuration_validator.py
Fixes https://github.com/takluyver/pynsist/issues/112
If you only want to support starting with a newline for `packages`, `pypi_wheels` and `exclude` you just need to add `.strip()` before `.splitlines()` here.
https://github.com/takluyver/pynsist/blob/9cd4cd73e04d52b6b22353dce7d2e3bed9fd8f7f/nsist/__init__.py#L543-L544
=> Allowing config values to start with a newline

nsist/__init__.py
I noticed the `publisher` parameter was not mentioned in the API documentation so I'm adding it here.
Check if it needs a more detailed description.
=> Add publisher entry to the docstring

nsist/pypi.py
Apparently, EEXIST is not reliable, but if the directory exists that would definitely raise an OSError. That's the only acceptable error case, so allow only that. The current implementation would cause problems if the path exists and is a file.
This is copying the CPython implementation: https://github.com/python/cpython/blob/master/Lib/pathlib.py#L1219
Related to takluyver/pynsist#118
=> Handle mkdir error like Python 3.5

nsist/__init__.py
When launching new child processes from an application packaged by pynsist the `pkgs` directory is **NOT** in `sys.path` causing import errors in the child process. The rule about `._pth` files applies (from the CPython source here: https://github.com/python/cpython/blob/3.6/PC/getpathp.c#L49):
`In the presence of this ._pth file, no other paths are added to the
search path, the registry finder is not enabled, site.py is not imported
and isolated mode is enabled. The site package can be enabled by
including a line reading "import site"; no other imports are recognized.
Any invalid entry (other than directories that do not exist) will result
in immediate termination of the program.`
This PR fixes the problem by ensuring the `pkgs` directory is referenced in the `._pth` files that may be …
=> Add pkgs to *._pth files.

doc/cfgfile.rst, nsist/__init__.py, nsist/pypi.py
Teach extract_wheel() to handle exclude patterns.  This allows us to
filter paths out of wheels, which can be helpful in many situations.
=> pynsist: make the "exclude" option work with pypi_wheels

nsist/__init__.py
The "commands" template calls the install directory
"installdir", but entry points call it "scriptdir".
Add an "installdir" variable to entry points for compatibility.  This
increases the chances of being able to reuse an "extra_preamble" script
across commands and entry points.
=> nsist: provide an "installdir" variable for consistency

doc/cfgfile.rst, nsist/__init__.py, nsist/copymodules.py, nsist/pypi.py, nsist/util.py
Canonicalize paths to their Unix representation when comparing fnmatch
patterns.  This makes patterns work across platforms, and
simplifies usage by providing a consistent interface to the
exclude patterns.
Closes #39
=> nsist: use "/" when comparing fnmatch patterns

doc/installers.rst
Not sure this is in the right place, so please feel free to move and/or change it as you see fit.
FYI: The work done in Mu to automate this can be found in this PR: https://github.com/mu-editor/mu/pull/391 and makes use of this repository: https://github.com/mu-editor/mu_tkinter
=> Add documentation about packaging with tkinter.

nsist/copymodules.py, nsist/pypi.py, nsist/tests/test_pypi.py
Following #160.
This PR modify the wheel and modules copy process to ensure that the package metadata (either *.dist-info or *.egg-info) are inserted in the pkgs directory before the installer is built.
This allows to use the plugins discovery mechanism inside a python application installed through the generated NSIS installer.
Regards,
Adrien Ferrand
=> Copy package metadata from wheels and from modules

README.rst, doc/cfgfile.rst, nsist/__init__.py, nsist/configreader.py, nsist/pypi.py, nsist/tests/test_local_wheels.py
Following #163 where we specified a mechanism to include local wheel files matching a path pattern.
Here is the PR to include all wheel files matching a list of glob paths specified in the `local_wheels` parameter, located under the `[Include]` section.
Matching wheel files will be processed into the installer the same way than wheels found from `wheels_pypi`.
Furthermore, any of the following situation will raise an error:
* two wheels to be included for the same distribution name
* a wheel to be included not compatible with the python version in the installer, or not compatible with Windows platforms.
=> Create a local_wheels parameter to include wheel files matching one or more glob paths

.gitignore, .travis.yml, appveyor.yml, nsist/tests/test_commands.py, nsist/tests/test_configuration_validator.py, nsist/tests/test_copymodules.py, nsist/tests/test_installerbuilder.py, nsist/tests/test_local_wheels.py, nsist/tests/test_pypi.py, nsist/tests/utils.py, tox.ini
Note: this PR should be merged only after #164, as it includes its changes (everything up to ca76f3c included).
Nose seems to be outdated and not maintained anymore. It is advised on their website to use another test framework. Furthermore I had some difficulties to make nose run correctly tests.
Pytest is the de facto standard test framework in Python. Tox is the widely used tool to prepare test environment for pytest. Both of them are unlikely to be dropped.
This PR implements pytest+tox to be used in the CI systems AppVeyor and Travis. Doing so the test environment is configured in a common location for both Windows and Linux (`tox.ini`). Additionally to the test environment run by default, a `notnetwork` is settled to execute tests on a machine without network: it takes advantage of …
=> Use tox+pytest to execute the tests, map to the CI systems

nsist/_system_path.py, nsist/pyapp.nsi
Fixes #167
If you have an application that installs commands, please test this branch! Check out the branch and install Pynsist from it (`flit install`), then use Pynsist to build a new installer. Install it and check that the directory containing exes is added to PATH correctly, then uninstall and check that the directory is removed from PATH again. Try the same with both a single-user installation and an installation for all users.
=> Fix adding commands to PATH in a user install

doc/cfgfile.rst, nsist/_assemble_launchers.py, nsist/commands.py, nsist/configreader.py, nsist/pyapp.nsi, nsist/tests/data_files/valid_config_with_commands.cfg, nsist/tests/test_commands.py, nsist/tests/test_configuration_validator.py
As described in #169
Adds an optional `console` property to the command sections with default value `true`. If set to `false`, the command's launcher will be built from one of the GUI launchers of `simple_launcher` and a shebang with `pythonw.exe` will be included instead of `python.exe`.
Changes:
- extend configreader with new `console` command property
- copy both launchers as dat-files (`launcher_exe.dat` and `launcher_noconsole_exe.dat`)
- split between `command-append.zip` and `command-append-noconsole.zip`, depending on the command's `console` value
- rewrite `_assemble_launchers.py` to reflect these changes and change its argvs so that the shebang can be tested
- add/rewrite tests
- add documentation
I haven't actually built any installers with these changes yet, but the updated …
=> Implement `console` command section property

nsist/pyapp.nsi
As of NSIS 3.05, ANSI targets are deprecated. Scripts compiled with that version will output a warning:
> 7998: ANSI targets are deprecated
This PR will always create Unicode installers if supported by the compiler.
**Related Links:**
- [Changelog](https://nsis.sourceforge.io/Docs/AppendixF.html#v3.05-rl)
- [StackOverflow](https://stackoverflow.com/a/51484760/1329116) (answer provided by NSIS developer [Anders Kjersem](https://nsis.sourceforge.io/Docs/AppendixH.html#programmers))
=> Create Unicode installer, if supported

doc/cfgfile.rst
I had some problems with the win32api module not being found. I traced it to the `.pth` files not being run, which i believe the above changes address https://pynsist.readthedocs.io/en/latest/_modules/nsist.html
=> Update cfgfile.rst - boilerplate for script should add pkgs\ as sitedir to load all .pth

nsist/tests/test_pypi.py, nsist/wheels.py
This removes the "m" suffix from the CPython ABI tags in the `CompatibilityScorer.score_abi` method if the python version is `>=3.8`.
In comparison to PR #192, this PR
- compares the python versions as a tuple of integers
- doesn't add the suffix-less name as a higher score item, as ABI suffixes shouldn't exist on `>=3.8`
(if this is wrong or you want to have full compatibility, even for "invalid" names, then I can of course update this)
- adds/updates tests
----
- https://docs.python.org/3/whatsnew/3.8.html#build-and-c-api-changes
- https://github.com/pypa/wheel/blame/0.35.1/docs/news.rst#L54
- https://github.com/pypa/wheel/blob/0.35.1/src/wheel/bdist_wheel.py#L80-L85
=> No ABI suffix in wheel names on Python >=3.8

doc/examples.rst
Ref: https://github.com/takluyver/pynsist/issues/214
=> removed dead links from example applications

.github/workflows/test.yml, README.rst, appveyor.yml, nsist/tests/test_pypi.py, nsist/wheels.py, pyproject.toml, tox.ini
Following [a discussion on the Python Discourse forum](https://discuss.python.org/t/python-tags-specific-version-of-interpreter-or-minimum-version/7831), the consensus is that a `cp36` Python tag is compatible with Python >= 3.6. But also, in the absence of a spec properly defining what tags are valid in any given situation, the answers in the [packaging.tags](https://packaging.pypa.io/en/latest/tags.html) module are definitive.
I was thinking of importing and using `packaging.tags`, but a) it handles a lot more cases than we need here, making it harder to follow all the logic, and b) it's built around the assumption that you want wheels for the Python it's running in, which is not the aim here. It's possible to override this assumption by supplying all inputs, but it's not easy to get …
=> Handle wheel tag compatibility like packaging.tags

examples/pygi_mpl_numpy/pygi_test.py
There is a small typo in examples/pygi_mpl_numpy/pygi_test.py.
Closes #229
=> docs: fix simple typo, conists -> consists

examples/pyqt5/installer.cfg
Python and PyQt5 versions were maxed out for Windows 7 compatibility. See https://github.com/takluyver/pynsist/issues/239
=> updated packages of the pyqt5 example

nsist/pyapp.nsi
See https://github.com/takluyver/pynsist/issues/66#issuecomment-1072518911
I've added a template comment with an example to make the intentions as clear as possible. If you don't agree with this, I will remove it again.
I'd also very much appreciate a new release if this gets merged, so that I can continue with my work and remove the ugly workaround we've been using in our installer. Thanks!
=> Add install_pkgs block to pyapp.nsi template

.github/workflows/test.yml, .readthedocs.yml, doc/conf.py, doc/pypi-requirements.txt, pyproject.toml
- Update Github action versions
- Remove Python 3.6 from Github actions
- Add newer Pythons up to 3.12
- Add the config file which is now required for readthedocs
=> Update CI config for 2024

nsist/__init__.py
In script mode, previously the shortcut would use the entire path provided in the config file rather than the filename of the script, resulting in a broken path and useless shortcut
Previous NSIS script
``` 
; Install shortcuts
; The output path becomes the working directory for shortcuts
SetOutPath "%HOMEDRIVE%\%HOMEPATH%"
CreateShortCut "$SMPROGRAMS\MyScript.lnk" "$INSTDIR\Python\pythonw.exe" \
'"$INSTDIR\../scripts/script.py"' "$INSTDIR\glossyorb.ico"
SetOutPath "$INSTDIR"
```
New NSIS script
```
; Install shortcuts
; The output path becomes the working directory for shortcuts
SetOutPath "%HOMEDRIVE%\%HOMEPATH%"
CreateShortCut "$SMPROGRAMS\MyScript.lnk" "$INSTDIR\Python\pythonw.exe" \
'"$INSTDIR\script.py"' "$INSTDIR\glossyorb.ico"
SetOutPath "$INSTDIR"
```
=> Fix shortcut target path when using script
